Entities/Product.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmagClone.Entities
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Stock { get; set; }
        // Todo stock/Reviews
        public Guid SellerId { get; set; }
        public virtual User Seller { get; set; }

        public virtual ICollection<Review> Reviews { get; set; }
        public ICollection<CartProductsUsers> cartProducts { get; set; }
        public ICollection<FavoriteProductsUsers> favoriteProducts { get; set; }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmagClone.Entities;
using OldIronIronWeTake.Data;
using EmagClone.Services;
using Microsoft.AspNetCore.Identity;
using System.Diagnostics;

namespace EmagClone.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ProductService service;
        private readonly UserManager<User> manager;
        public ProductsController(ProductService service, UserManager<User> manager)
        {
            this.service = service;
            this.manager = manager;
        }

        // GET: Products
        public async Task<IActionResult> Index(string keyword)
        {
            if (keyword == null || keyword == "")
            {
                ViewBag.prods = service.GetAll();
                return View(service.GetAll());
            }

            return View(service.Search(keyword));

        }


        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = service.Get((int)id);
            //Debug.WriteLine("ceva string" + product.SellerId);
            //Debug.WriteLine("ceva string 2 " + product.Seller == null);
            //Debug.WriteLine("ceva string 3 " + product.Seller.UserName);

            if (product == null)
            {
                return NotFound();
            }

            //Debug.WriteLine(product.Reviews.Count());
            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Stock")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.SellerId = (await manager.GetUserAsync(HttpContext.User)).Id;
                Debug.Assert(service.Post(product));
                //service.Post(product);
                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = service.Get((int)id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Stock,SellerId")] Product product)
        { 

            if (ModelState.IsValid)
            {
                bool check = service.Update(product, (int)id);
                Debug.Assert(service.Update(product, (int)id));
                if (!check)
                {
                    return NotFound();
                }
                
                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }


        // POST: Products/Delete/5
        //[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            bool check = service.Delete(id);
            Debug.Assert(check);
            if (!check)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmagClone.Entities;
using OldIronIronWeTake.Data;
using EmagClone.Services;
using Microsoft.AspNetCore.Identity;

namespace EmagClone.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ReviewService service;
        private readonly UserManager<User> manager;

        public ReviewsController(ReviewService service, UserManager<User> manager)
        {
            this.service = service;
            this.manager = manager;
        }

        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //Review r = new Review();
            //r.ProductId = (int)id;
            //r.UserId = (Guid)UserId;

            ViewData["ProductId"] = (int)id;
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Text,")] Review review)
        public async Task<IActionResult> Create([Bind("ProductId,Text")] Review review)
        {
            if (ModelState.IsValid)
            {
                var user = await manager.GetUserAsync(HttpContext.User);
                review.User = user;

                service.Post(review);
                return Redirect("/Products/Details/" + review.ProductId);
            }
            return View();
        }

        //// GET: Reviews/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var review = await _context.Reviews.FindAsync(id);
        //    if (review == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", review.ProductId);
        //    ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", review.UserId);
        //    return View(review);
        //}

        //// POST: Reviews/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,Text,ProductId,UserId")] Review review)
        //{
        //    if (id != review.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(review);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!ReviewExists(review.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id", review.ProductId);
        //    ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", review.UserId);
        //    return View(review);
        //}

        //// GET: Reviews/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var review = await _context.Reviews
        //        .Include(r => r.Product)
        //        .Include(r => r.User)
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (review == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(review);
        //}

        //// POST: Reviews/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var review = await _context.Reviews.FindAsync(id);
        //    _context.Reviews.Remove(review);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool ReviewExists(int id)
        //{
        //    return _context.Reviews.Any(e => e.Id == id);
        //}
    }
}

Controllers/UsersController.cs
using EmagClone.Entities;
using EmagClone.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OldIronIronWeTake.Data;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EmagClone.Controllers
{
    public class UsersController : Controller
    {

        private readonly UserManager<User> manager;
        private FavoritesService favoritesService;
        private CartService cartService;
        private ProductService products;
        private readonly ApplicationDbContext context;

        public UsersController(UserManager<User> userManager, ProductService products, FavoritesService favoritesService, CartService cart, ApplicationDbContext context)
        {
            this.manager = userManager;
            this.favoritesService = favoritesService;
            cartService = cart;
            this.products = products;
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Profile(Guid id)
        {
            return View(products.GetByUser(id));
        }

        [Authorize(Roles = "User,Store,Admin")]
        public async Task<IActionResult> Cart()
        {
            var user = (await manager.GetUserAsync(HttpContext.User));
            return View(cartService.GetAll(user));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User,Store,Admin")]
        public async Task<IActionResult> AddToCart(int id)
        {
            if (ModelState.IsValid)
            {
                var user = (await manager.GetUserAsync(HttpContext.User));
                bool check = cartService.AddToCart(id, user);
                Debug.Assert(check);
                if (!check)
                {
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction(nameof(Cart));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User,Store,Admin")]
        public async Task<IActionResult> RemoveFromCart(int id)
        {
            if (!cartService.RemoveFromCart(id))
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Cart));
        }

        public async Task<IActionResult> Order()
        {
            return View();
        }

        [Authorize(Roles = "User,Store,Admin")]
        public async Task<IActionResult> Favorites()
        {
            var user = (await manager.GetUserAsync(HttpContext.User));
            return View(favoritesService.GetAll(user));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User,Store,Admin")]
        public async Task<IActionResult> AddFavorite(int id)
        {
            if (ModelState.IsValid)
            {
                var user = (await manager.GetUserAsync(HttpContext.User));
                bool check = favoritesService.AddToFavorites(id, user);
                Debug.Assert(check);
                if (!check)
                {
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction(nameof(Favorites));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User,Store,Admin")]
        public async Task<IActionResult> RemoveFavorite(int id)
        {
            var check = favoritesService.RemoveFromFavorites(id);
            Debug.Assert(check);
            if (!check)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Favorites));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<bool> Delete(Guid id)
        {
            User user = context.Users.Find(id);

            if (user == null)
            {
                return false;
            }

            context.Users.Remove(user);
            context.SaveChanges();
            return true;

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<bool> Toggle(Guid id)
        {
            User user = context.Users.Find(id);

            if (user == null)
            {
                return false;
            }

            if ((await manager.GetRolesAsync(user)).Contains("Store"))
            {
                await manager.RemoveFromRoleAsync(user, "Store");
            }
            else
            {
                await manager.AddToRoleAsync(user, "Store");
            }

            return true;
        }

    }
}

Views/Products/Create.cshtml
@model EmagClone.Entities.Product

@{
    ViewData["Title"] = "Add product";
}

<h1>Add product</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="List item" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Products/Details.cshtml
@model EmagClone.Entities.Product

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Name)</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Stock)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Stock)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Seller)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Users" asp-action="Profile" asp-route-id="@Model.SellerId">
                @Html.DisplayFor(model => model.Seller.UserName)
            </a>
</dd>
    </dl>
</div>

<div>
    <a asp-controller="Reviews" asp-action="Create" asp-route-id="@Model.Id">Add Review</a>
    <form asp-controller="Users" method="post" asp-action="AddFavorite" asp-route-id="@Model.Id"><a id="delete" onclick="this.parentElement.submit()">Add to favorites</a></form>
    <form asp-controller="Users" method="post" asp-action="AddToCart" asp-route-id="@Model.Id"><a id="delete" onclick="this.parentElement.submit()">Add to cart</a></form>

</div>
@if ((Model.Seller.UserName == Context.User.Identity.Name && User.IsInRole("Store")) || User.IsInRole("Admin"))
{
    <div>
        <a asp-controller="Products" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
        <form method="post" asp-controller="Products" asp-action="Delete" asp-route-id="@Model.Id"><a id="delete" onclick="this.parentElement.submit()">Delete</a></form>
    </div>
}

@*<div>
        @if (Model.Reviews != null)
        {
            @foreach (var x in Model.Reviews)
            {
                <p>@x.User.UserName</p>
                <p>@x.Text</p>

                @if ((Model.Seller.UserName == Context.User.Identity.Name && User.IsInRole("Store")) || User.IsInRole("Admin"))
                {
                    <a asp-controller="Reviews" asp-action="Delete" asp-route-id="@x.Id">Delete</a>
                }
            }
        }

    </div>*@

<br />
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                Username
            </th>
            <th>
                Review
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Reviews != null)
        {
            @foreach (var item in Model.Reviews)
            {
                <tr>
                    <td>
                        <a asp-controller="Users" asp-action="Profile" asp-route-id="@item.UserId">@item.User.UserName</a>

</td>
                    <td>
                        @item.Text
                    </td>

                </tr>
            }
        }
    </tbody>
</table>

Views/Products/Edit.cshtml
@model EmagClone.Entities.Product

@{
    ViewData["Title"] = "Edit";
}


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save changes" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Products/Index.cshtml
@model IEnumerable<EmagClone.Entities.Product>

@{
    ViewData["Title"] = "All products";
}

<h1>All products</h1>
<form asp-action="Index">
    <input type="text" placeholder="Search.." name="keyword">
    <button type="submit">Submit</button>
</form>

<p>
    @if (User.IsInRole("Store") || User.IsInRole("Admin"))
    {
        <a asp-action="Create">Add product</a>
    }
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seller)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stock)
                </td>
                <td>
                    <a asp-controller="Users" asp-action="Profile" asp-route-id="@item.SellerId">@Html.DisplayFor(modelItem => item.Seller.UserName)</a>
                </td>
                @if ((item.Seller.UserName == Context.User.Identity.Name && User.IsInRole("Store")) || User.IsInRole("Admin"))
                {
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <form method="post" asp-action="Delete" asp-route-id="@item.Id"><a id="delete" onclick="this.parentElement.submit()">Delete</a></form>

                    </td>
                }
                @if (User.IsInRole("Admin"))
                {
                    <td>
                        <form method="post" asp-controller="Users" asp-action="Delete" asp-route-id="@item.SellerId"><a id="delete" onclick="this.parentElement.submit()">Delete</a></form>
                        <form method="post" asp-controller="Users" asp-action="Toggle" asp-route-id="@item.SellerId"><a id="delete" onclick="this.parentElement.submit()">Toggle</a></form>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>